In [1]:
import numpy as np

q1 = np.array([
    [200, 220, 250],
    [150, 180, 210],
    [300, 330, 360]
])
q2 = np.array([
    [209, 231, 259],
    [155, 192, 222],
    [310, 340, 375]
])

q1+q2
        

array([[409, 451, 509],
       [305, 372, 432],
       [610, 670, 735]])

In [2]:
q2-q1

array([[ 9, 11,  9],
       [ 5, 12, 12],
       [10, 10, 15]])

In [6]:
(q2-q1) * 100/q1

array([[4.5       , 5.        , 3.6       ],
       [3.33333333, 6.66666667, 5.71428571],
       [3.33333333, 3.03030303, 4.16666667]])

In [7]:
price = np.array([
    [10, 12, 11],
    [8, 9, 10],
    [15, 16, 17]
])
price

array([[10, 12, 11],
       [ 8,  9, 10],
       [15, 16, 17]])

In [9]:
q1 * price

array([[2000, 2640, 2750],
       [1200, 1620, 2100],
       [4500, 5280, 6120]])

In [10]:
q1 * price * 0.80

array([[1600., 2112., 2200.],
       [ 960., 1296., 1680.],
       [3600., 4224., 4896.]])

In [12]:
np.sum(q1 * price * 0.80)

np.float64(22568.0)