In [9]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [8, 7, 6, 5]], dtype = np.float64)
arr.dtype

dtype('float64')

In [10]:
arr.ndim

2

In [11]:
arr.itemsize

8

In [12]:
arr.size

8

In [13]:
arr.shape

(2, 4)

In [14]:
np.sort(arr)

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [18]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [19]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [20]:
np.arange(10, 100, 10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
np.linspace(0, 100, 5)

array([  0.,  25.,  50.,  75., 100.])

In [27]:
arr.ravel()

array([1., 2., 3., 4., 8., 7., 6., 5.])

In [30]:
print(arr.min())

1.0


In [31]:
print(arr.max())

8.0


In [34]:
print(arr.sum(axis = 0))

[9. 9. 9. 9.]


In [35]:
np.sqrt(arr)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [2.82842712, 2.64575131, 2.44948974, 2.23606798]])

In [36]:
np.square(arr)

array([[ 1.,  4.,  9., 16.],
       [64., 49., 36., 25.]])